-- Control your input devices
-- See https://wiki.hypr.land/Configuring/Variables/#input
-- Generated by hyprlang2lua. Review TODOs before reloading Hyprland.

hl.window_rule({
    match = {
        class = "(Alacritty|kitty|foot)",
    },
    scroll_touchpad = 1.5,
})

hl.gesture({
    fingers = 4,
    direction = "up",
    action = function()
        hl.exec_cmd("quickshell ipc -p "..os.getenv("HOME").."/x call expose toggle")
    end,
})

hl.config({
    input = {
        kb_layout = "es",
        kb_options = "compose:caps", -- ,grp:alts_toggle
        -- Change speed of keyboard repeat
        repeat_rate = 40,
        repeat_delay = 600,
        touchpad = {
            -- Use natural (inverse) scrolling
            -- natural_scroll = true
            -- Use two-finger clicks for right-click instead of lower-right corner
            clickfinger_behavior = true,
            -- Control the speed of your scrolling
            scroll_factor = 0.4,
            -- Disable the touchpad while typing
            disable_while_typing = true,
            -- Disable tap to clik
            tap_to_click = true,
        },
    },
    gestures = {
        workspace_swipe_invert = true, -- Set to false to reverse the inversion
    },
})
